name: iot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - python-dotenv=1.1.0
  - flask=3.1.1
  - jinja2=3.1.6
  - mysql-connector-python=8.2.0
  - jsonpickle=4.1.1
  - pip=25.1.1
  - matplotlib=3.10.3