-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 23:18:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

START TRANSACTION;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iot` ;

-- -----------------------------------------------------
-- Schema iot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iot` DEFAULT CHARACTER SET utf8 ;
USE `iot` ;

-- -----------------------------------------------------
-- Table `iot`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot`.`users` ;

CREATE TABLE IF NOT EXISTS `iot`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot`.`rfid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot`.`rfid` ;

CREATE TABLE IF NOT EXISTS `iot`.`rfid` (
  `rfidId` INT NOT NULL AUTO_INCREMENT,
  `rfidValue` CHAR(12) NOT NULL,
  PRIMARY KEY (`rfidId`),
  UNIQUE INDEX `rfidId_UNIQUE` (`rfidId` ASC) VISIBLE,
  UNIQUE INDEX `rfidValue_UNIQUE` (`rfidValue` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot`.`user_identifier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot`.`user_identifier` ;

CREATE TABLE IF NOT EXISTS `iot`.`user_identifier` (
  `userIdentifierId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `rfidId` INT NOT NULL,
  `disabled` BIT NOT NULL DEFAULT 0,
  INDEX `fk_user_identifier_user1_idx` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `rfid_rfidId_UNIQUE` (`rfidId` ASC) VISIBLE,
  PRIMARY KEY (`userIdentifierId`),
  UNIQUE INDEX `userIdentifierId_UNIQUE` (`userIdentifierId` ASC) VISIBLE,
  CONSTRAINT `fk_user_identifier_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `iot`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_identifier_rfid1`
    FOREIGN KEY (`rfidId`)
    REFERENCES `iot`.`rfid` (`rfidId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot`.`entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot`.`entry` ;

CREATE TABLE IF NOT EXISTS `iot`.`entry` (
  `userIdentifierId` INT NOT NULL,
  `entryTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  INDEX `fk_entry_user_identifier1_idx` (`userIdentifierId` ASC) VISIBLE,
  CONSTRAINT `fk_entry_user_identifier1`
    FOREIGN KEY (`userIdentifierId`)
    REFERENCES `iot`.`user_identifier` (`userIdentifierId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot`.`temperature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot`.`temperature` ;

CREATE TABLE IF NOT EXISTS `iot`.`temperature` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `measured_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `value_celsius` FLOAT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot`.`motor_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot`.`motor_event` ;

CREATE TABLE IF NOT EXISTS `iot`.`motor_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `userId` INT NULL,
  `action` VARCHAR(32) NOT NULL,
  `speed` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_motor_event_userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_motor_event_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `iot`.`users` (`userId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot`.`motor_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot`.`motor_config` ;

CREATE TABLE IF NOT EXISTS `iot`.`motor_config` (
  `id` INT NOT NULL,
  `speed_pct` FLOAT NOT NULL,
  `critical_temp` FLOAT NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Insert example data
-- -----------------------------------------------------

INSERT INTO `iot`.`users` VALUES (NULL, 'Gipsz Jakab');
INSERT INTO `iot`.`users` VALUES (NULL, 'Nagy Paszkál');
INSERT INTO `iot`.`users` VALUES (NULL, 'Kiss Béla');

INSERT INTO `iot`.`rfid` VALUES (NULL, '3100821010');
INSERT INTO `iot`.`rfid` VALUES (NULL, '1913502801');

INSERT INTO `iot`.`user_identifier` VALUES (NULL, 1,1,0);
INSERT INTO `iot`.`user_identifier` VALUES (NULL, 2,2,1);

INSERT INTO `iot`.`motor_config` VALUES (1, 25.0, 5.0);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

commit;